Javascript/javascript1/week2
JyothiNandyala/hyf-homework pull request #4
Opened 2020-11-04 09:14 UTC by JyothiNandyala

Adding the javascript1 week2 homework.

2020-11-05 19:21 UTC, aina21 requested changes
Good job 👍

2020-11-05 19:21 UTC, aina21 commented on git/week1/eventapplication.js
> +  let eventDay=((date.getDay()+number)+7)%7;
use const, and I don't understand why do you plus with 7?

2020-11-05 19:21 UTC, aina21 commented on git/week1/candyhelper.js
> +let boughtCandyPrices =[]
const

2020-11-05 19:21 UTC, aina21 commented on git/week1/candyhelper.js
> +       let  price=weight*0.5;
you use a price out of scope, so maybe it is better to defined before if

2020-11-05 19:21 UTC, aina21 commented on git/week1/candyhelper.js
> +    if(candyType==="Sweet"){
maybe switch is more readable here

2020-11-05 19:21 UTC, aina21 commented on git/week1/candyhelper.js
> +let amountToSpend =Math.random() * 100;
const

2020-11-05 19:21 UTC, aina21 commented on git/week1/candyhelper.js
> +if(totalPrice>amountToSpend){
What about time the totalprice is equal to the amountToSpend.

2020-11-11 17:59 UTC, JyothiNandyala commented
Hi Ida,

i have changed my comments and pushed to github,could you please  check and
let me know.

Thanks&Regards
Jyothi.

On Fri, Nov 6, 2020 at 12:51 AM Ida Naderian <notifications@github.com>
wrote:

> *@aina21* requested changes on this pull request.
>
> Good job 👍
> ------------------------------
>
> In git/week1/studentmanager.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518283659>
> :
>
> > @@ -0,0 +1,46 @@
>
> +
>
> +const class07Students = [];
>
> +function addStudentToClass(studentName){
>
> +
>
> +if(studentName==="Denmark Queen"){
>
> +     if(class07Students.length<6 || class07Students.length>=6){
>
>
> Do you need this condition?
> ------------------------------
>
> In git/week1/studentmanager.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518285589>
> :
>
> > +}
>
> +//console.log(class07Students);
>
> +addStudentToClass("jyothi")
>
> +addStudentToClass("sandhana")
>
> +addStudentToClass("rajani")
>
> +addStudentToClass("charmi")
>
> +addStudentToClass("tithi")
>
> +addStudentToClass("Denmark Queen")
>
> +addStudentToClass("Nitheesha")
>
> +
>
> +
>
> +console.log(class07Students);
>
> +
>
> +function getNumberOfStudents() {
>
> +  // You write code here
>
> +  var length=class07Students.length;
>
>
> Don't use var here :)
> ------------------------------
>
> In git/week1/flightBooking.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518286628>
> :
>
> > @@ -0,0 +1,32 @@
>
> +
>
> +function getFullname(firstname ,surname) {
>
> +
>
> +    return firstname + ' ' + surname;
>
> +
>
> +    }
>
> +const fullName=getFullname("jyothi" ,"Nandyala");
>
> +console.log(fullName);
>
> +
>
> +
>
> +//Creating two varables
>
> +
>
> +var fullName1=getFullname("sree" ,"Nani");
>
>
> don't use var
> ------------------------------
>
> In git/week1/eventapplication.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518287208>
> :
>
> > @@ -0,0 +1,16 @@
>
> +
>
> +var weekday = ["Sunday" ,"Monday" ,"Tuesday" ,"Wednesday" ,"Thursday" ,"Friday" ,"Saturday"]
>
>
> don't use var :D
> ------------------------------
>
> In git/week1/eventapplication.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518295966>
> :
>
> > @@ -0,0 +1,16 @@
>
> +
>
> +var weekday = ["Sunday" ,"Monday" ,"Tuesday" ,"Wednesday" ,"Thursday" ,"Friday" ,"Saturday"]
>
> +var date = new Date();
>
> +var day = weekday[date.getDay()];
>
> +console.log(day);
>
> +var eventHeldDay=4;
>
> +function getEventWeekday(number){
>
> +
>
> +  let eventDay=((date.getDay()+number)+7)%7;
>
>
> use const, and I don't understand why do you plus with 7?
> ------------------------------
>
> In git/week1/candyhelper.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518296458>
> :
>
> > @@ -0,0 +1,44 @@
>
> +
>
> +let boughtCandyPrices =[]
>
>
> const
> ------------------------------
>
> In git/week1/candyhelper.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518296564>
> :
>
> > @@ -0,0 +1,44 @@
>
> +
>
> +let boughtCandyPrices =[]
>
> +
>
> +function addCandy(candyType ,weight){
>
> +    if(candyType==="Sweet"){
>
> +       let  price=weight*0.5;
>
>
> you use a price out of scope, so maybe it is better to defined before if
> ------------------------------
>
> In git/week1/candyhelper.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518297386>
> :
>
> > @@ -0,0 +1,44 @@
>
> +
>
> +let boughtCandyPrices =[]
>
> +
>
> +function addCandy(candyType ,weight){
>
> +    if(candyType==="Sweet"){
>
>
> maybe switch is more readable here
> ------------------------------
>
> In git/week1/candyhelper.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518297646>
> :
>
> > +    else if(candyType==="Toffee"){
>
> +         price=weight*1.1;
>
> +        boughtCandyPrices.push(price);
>
> +    }else if(candyType==="Chewing-gum"){
>
> +         price=weight*0.03;
>
> +     boughtCandyPrices.push(price);
>
> +
>
> +    }
>
> +
>
> +}
>
> +addCandy("sweet", 20);
>
> +addCandy("Chocolate", 20);
>
> +addCandy("Toffee", 20);
>
> +addCandy("Chewing-gum", 20);
>
> +
>
> +let amountToSpend =Math.random() * 100;
>
>
> const
> ------------------------------
>
> In git/week1/candyhelper.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518302709>
> :
>
> > +}
>
> +addCandy("sweet", 20);
>
> +addCandy("Chocolate", 20);
>
> +addCandy("Toffee", 20);
>
> +addCandy("Chewing-gum", 20);
>
> +
>
> +let amountToSpend =Math.random() * 100;
>
> +console.log(amountToSpend);
>
> +let totalPrice=0;
>
> +for(let i=0;i<boughtCandyPrices.length;i++){
>
> +    totalPrice=totalPrice+boughtCandyPrices[i];
>
> +    console.log(totalPrice);
>
> +}
>
> +
>
> +function canBuyMoreCandy(){
>
> +if(totalPrice>amountToSpend){
>
>
> What about time the totalprice is equal to the amountToSpend.
> ------------------------------
>
> In git/week1/studentmanager.js
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#discussion_r518284352>
> :
>
> > @@ -0,0 +1,46 @@
>
> +
>
> +const class07Students = [];
>
> +function addStudentToClass(studentName){
>
> +
>
> +if(studentName==="Denmark Queen"){
>
> +     if(class07Students.length<6 || class07Students.length>=6){
>
>
> what if we add "Denmark Queen" twice?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JyothiNandyala/hyf-homework/pull/4#pullrequestreview-524564443>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARCQJSDV67OL3WZPO72SGVDSOL3NNANCNFSM4TJZJS5Q>
> .
>

2020-11-14 22:34 UTC, aina21 commented
you have unrelated files for week1 in this PR, check your file path. you may get conflict if you merge it.

2020-11-15 15:34 UTC, merged